language: java

sudo: false

script: "mvn package --settings travis/settings.xml"

jdk:
  - oraclejdk8

env:
  global:
  - secure: "MeLq+CjCUG/EOz2CnB5cGK0pyiG5P+l9xSP4TrKm2wIWRRxVbjE/4Ysza2g45iluzvT/wZr6NDyY7NIydBUNokweJD6Z5eZ5R1v6h8wCQqSdgwzKitY7+lTNkX0Y4lslcO17qtXlt4xQwH0/ahmZlYqQZ4aiKVYmiDsvbNK8LZmV7184aSva7x3y9JPJwp+gcfpBuwjRml2G/K6CItHcd/qvsJZrzUIzi6NpTFuIal3QQBnc1riadVsEzXAjfExGAlm70D/ciM5bKyKncy8Pf1BlgJgxSMwOr4S73+1ZkaVyVPXWSxKiEneQuHpl1ycQUXYxMRmXOvVgCDlEvRkGMgqBdcm3bDzzru0qVBBrfG90bH9ozCOt+sNc6sh/o4z0SwMkhjK5TKw1NIIUM6UX/YHghiasFrTqkOwLUXbqg18PCgLqyzO/WjVqV5QsLIopgTSKC9MHL3rhX3caXjIKyiDruR3riTHjaGYm/7i8tf+jOICiGjozx9Sd1DW1YxaLN7W044z0tiou1H3LERowOO0cM82p5fvOeEUrYk2YVrW0PKi0H6VBGKzhOufjCYLwMcIO5Ep2g9A8tOK82hAj5HdGIIjddHENIsqsKczUBUeYjUqBPP1dzNFf2ObgjpU91/E+aKtzOLDupOCr4I+u7FQbt6AxqGBV+6nmCX3SGGI="
  - secure: "E/4zc8eLXfbLloT7C5EScJJG6diEnE5y9CdEQYGet7ZyL+VAJZ/hNufCa7RxoGKU0iHPu8SkWEn9bc0ac18uCALi8KV27npZhzDcmNSPcTYaSEItvF8jbiIyzJXg+fGUHlW/ofCSjCd1ZdJN/e4sFFQW22d7fL+EFwkRHM6eHUDyVTo9Yez/9seCuSZMYeqLJiEGsbnh7lBQeBXubNiDKQ10Xy6TB8oUwDlap7HmyJFT1hzuAahnBuvjPROAu6s4/V69dkAiJsEMymO6ImR5Hkc3fIKEME4VXpeydFsuUvAJxiK1JGJNEyYG9taSZszhej1+NRQQqdz8Xmdw4iZEMdKQO5krlmwiSm0H/gLjUXLD2HErCFMKyDSX7BEk+bxjjxRiukd40OvUWajJ7ae9nkzZYaPNjAraLPwd7vicBcbV56wbvIAQKNQDvuco1ZHpwCSwAXkoYfCEuDyIsFOxLdLrwT3l02bTzJ70ZhlFG1FJ/X5ew8r2AM9DW3cI4nVatEIzMcwEc7MRgTXrKTcK6nGqb/YF+hHlnRQHTNwAaKtU3Uvx0ddRr1LT8YxcpcO8Ith03aGGHekTML40gpzm1bsa1Mw4YplL98bvUWs1gduoMlSCF5UIqYtfaQzGG6lM5m7LhaCk9adgICGxVsm98rUA64iFj1NzWA3AnKLH8aE="

after_success:
- chmod -R 777 ./travis/deploy-to-sonatype.sh
- ./travis/deploy-to-sonatype.sh
